package com.aigardev.rolecenterapp.charactersheets

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.aigardev.rolecenterapp.core.data.models.GyGSheet
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class ListSheetsViewModel : ViewModel() {

    private val _uiState = MutableStateFlow<ListSheetsUiState>(ListSheetsUiState.Loading)
    val uiState: StateFlow<ListSheetsUiState> = _uiState.asStateFlow()

    init {
        // Simulación de carga de datos (reemplaza con tu lógica real)
        viewModelScope.launch {
            delay(1000) // Simula una carga de 2 segundos
            // _uiState.value = ListSheetsUiState.Success(emptyList()) // Inicialmente, la lista está vacía
            _uiState.value = ListSheetsUiState.Success( // Lista de prueba
                listOf(
                    GyGSheet(
                        id = 101,
                        name = "Aric el Veloz",
                        profession = "Cazador de Sombras",
                        race = "Elfo Silvano",
                        level = 1,
                        strength = 3,
                        agility = 6,
                        intelligence = 4,
                        charisma = 3,
                        lifePoints = 9,
                        combat = 4,
                        atk = 4,
                        def = 4,
                        knowledge = 3,
                        larceny = 6,
                        magic = 2,
                        social = 5,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 102,
                        name = "Faelar Cantaluna",
                        profession = "Encantador",
                        race = "Alto Elfo",
                        level = 1,
                        strength = 2,
                        agility = 3,
                        intelligence = 7,
                        charisma = 4,
                        lifePoints = 6,
                        combat = 2,
                        atk = 2,
                        def = 2,
                        knowledge = 7,
                        larceny = 3,
                        magic = 6,
                        social = 2,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 103,
                        name = "Brom Martillo Férreo",
                        profession = "Guardián Rúnico",
                        race = "Enano",
                        level = 1,
                        strength = 7,
                        agility = 2,
                        intelligence = 3,
                        charisma = 4,
                        lifePoints = 21,
                        combat = 6,
                        atk = 6,
                        def = 6,
                        knowledge = 4,
                        larceny = 2,
                        magic = 3,
                        social = 5,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 104,
                        name = "Lysandra Sombra Nocturna",
                        profession = "Asesina",
                        race = "Elfo Oscuro",
                        level = 1,
                        strength = 3,
                        agility = 7,
                        intelligence = 4,
                        charisma = 2,
                        lifePoints = 9,
                        combat = 5,
                        atk = 5,
                        def = 5,
                        knowledge = 2,
                        larceny = 7,
                        magic = 3,
                        social = 3,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 105,
                        name = "Torvin Piedraparla",
                        profession = "Druida",
                        race = "Gnomo de los Bosques",
                        level = 1,
                        strength = 2,
                        agility = 4,
                        intelligence = 6,
                        charisma = 4,
                        lifePoints = 6,
                        combat = 3,
                        atk = 3,
                        def = 3,
                        knowledge = 6,
                        larceny = 2,
                        magic = 5,
                        social = 4,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 106,
                        name = "Seraphina Vientoluz",
                        profession = "Bardo",
                        race = "Mediana",
                        level = 1,
                        strength = 2,
                        agility = 5,
                        intelligence = 4,
                        charisma = 5,
                        lifePoints = 6,
                        combat = 3,
                        atk = 3,
                        def = 3,
                        knowledge = 4,
                        larceny = 5,
                        magic = 3,
                        social = 5,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 107,
                        name = "Kazimir Garrasangre",
                        profession = "Bárbaro",
                        race = "Semi-Orco",
                        level = 1,
                        strength = 8,
                        agility = 4,
                        intelligence = 1,
                        charisma = 3,
                        lifePoints = 24,
                        combat = 7,
                        atk = 7,
                        def = 7,
                        knowledge = 1,
                        larceny = 5,
                        magic = 1,
                        social = 6,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 108,
                        name = "Elowen Hoja Danzante",
                        profession = "Guardabosques",
                        race = "Elfa Silvana",
                        level = 1,
                        strength = 4,
                        agility = 6,
                        intelligence = 3,
                        charisma = 3,
                        lifePoints = 12,
                        combat = 5,
                        atk = 5,
                        def = 5,
                        knowledge = 4,
                        larceny = 5,
                        magic = 2,
                        social = 4,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 109,
                        name = "Gareth Mano Plateada",
                        profession = "Ladrón",
                        race = "Humano",
                        level = 1,
                        strength = 3,
                        agility = 6,
                        intelligence = 4,
                        charisma = 3,
                        lifePoints = 9,
                        combat = 4,
                        atk = 4,
                        def = 4,
                        knowledge = 3,
                        larceny = 7,
                        magic = 2,
                        social = 4,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 110,
                        name = "Valeria Escudo de Roble",
                        profession = "Paladín",
                        race = "Humana",
                        level = 1,
                        strength = 6,
                        agility = 3,
                        intelligence = 3,
                        charisma = 4,
                        lifePoints = 18,
                        combat = 6,
                        atk = 6,
                        def = 6,
                        knowledge = 3,
                        larceny = 2,
                        magic = 4,
                        social = 5,
                        game = "Goblins & Grutas",
                    ),
                    GyGSheet(
                        id = 111,
                        name = "Jinx Ojosombrío",
                        profession = "Hechicero",
                        race = "Tiefling",
                        level = 1,
                        strength = 1,
                        agility = 4,
                        intelligence = 8,
                        charisma = 3,
                        lifePoints = 3,
                        combat = 2,
                        atk = 2,
                        def = 2,
                        knowledge = 5,
                        larceny = 3,
                        magic = 8,
                        social = 2,
                        game = "Goblins & Grutas",
                    )
                )
            )
        }
    }
}